language: generic
before_install:
  - sudo sh -c "echo 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.5 main' >> /etc/apt/sources.list"
  - sudo apt-get update -qq
script:
  - cd java/brainfrack; mvn package -q
  - cd ../..

  - cd clojure/brainfrack; LEIN_SILENT=true lein compile
  - cd ../..

  - cd haskell; ghc Brainfrack.hs
  - cd ..

  - cd c; make
  - cd ..
notifications:
  email: false
